# Generated by Django 4.1.1 on 2022-10-29 18:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("name", models.CharField(max_length=50)),
                ("mac_address", models.CharField(max_length=50, unique=True)),
                ("ip_number", models.CharField(max_length=20)),
                ("device_known", models.BooleanField(default=True)),
                ("device_prohibited", models.BooleanField(default=False)),
                ("device_connected", models.BooleanField(default=False)),
            ],
        ),
    ]
