# Generated by Django 4.1.1 on 2023-07-19 18:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "network_manager",
            "0003_host_nmaprun_runstat_remove_deviceport_device_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="nmaprun",
            name="date_run",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="host",
            name="vendor",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
