# Generated by Django 4.1.1 on 2023-07-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network_manager", "0004_nmaprun_date_run_alter_host_vendor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="host",
            name="times_rttvar",
        ),
        migrations.RemoveField(
            model_name="host",
            name="times_srtt",
        ),
        migrations.RemoveField(
            model_name="host",
            name="times_to",
        ),
        migrations.AddField(
            model_name="host",
            name="operating_system",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
