# Generated by Django 4.1.1 on 2023-07-20 08:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "network_manager",
            "0005_remove_host_times_rttvar_remove_host_times_srtt_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="host",
            name="first_discovered",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="host",
            name="last_seen",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
