# Generated by Django 4.1.1 on 2023-10-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "network_manager",
            "0007_remove_host_operating_system_host_cpe_host_os_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="runstat",
            name="finished_errormsg",
            field=models.TextField(blank=True, null=True),
        ),
    ]
